---
name: CI

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: python3 -m pytest tests
